import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
import './globals.css';
import { Seymour_One } from 'next/font/google';

const seymour_One = Seymour_One({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>, ) {
  return (
    <html lang="en">
      <head><link href="https://fonts.cdnfonts.com/css/docallisme-on-street" rel="stylesheet"/>
        <style>@import url('https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&family=Rubik+Spray+Paint&display=swap');
        </style>

        </head>
      
      <body>
          {children}
      </body>
    </html>
  );
}
